### ISSUE TITLE
hot reload with web  request

### ISSUE THREAD

**Issue by tsingson** [zhu327/pingsix#2]
api gateway often changes api and corresponding proxy, please consider to update uri / upstreams in real time without restarting the proxy. And real time update can be operated via web.

This is like the sozu project (but without the web interface).

I can help with the web impl ( via react  / TS ).

thanks

**Comment by zhu327** [comment]
https://github.com/cloudflare/pingora/blob/main/docs/user_guide/graceful.md

Currently, pingsix can achieve graceful restart. In the future, there are plans to add real-time resource loading of etcd compatible with apisix data. Right now, the focus is still on refining basic functionalities, such as defining plugin traits. 

Since I am not very skilled in front-end development, the plan for this project was to directly use apisix's Dashboard. It would be great if you could help contribute code together!

**Comment by tsingson** [comment]
cool.
